### ISSUE TITLE
Malfunction in getting remotes as of commit 'Improve RemoteURL handling of no valid remote'

### ISSUE THREAD

**Issue by siebenmann** [shurcooL/vcsstate#3]
This commit changes git.go to try to run `git remote get-url origin`. Unfortunately this git-remote option is only supported in relatively recent versions of git; apparently it only appeared in git 2.7. Fedora 23 has git version 2.5.5; Ubuntu 14.04 has git version 1.9.1. Other systems may have even older versions. On anything short of 2.7, the net effect is that gostatus (and presumably anything else using vcsstate) thinks everything doesn't have a remote because trying to run the git-remote command errors out as git-remote complains that it has no get-url subcommand.

(This is commit 80ebbe9a32cc665d29da8acd66155331974fa7f8 .)

**Comment by dmitshur** [comment]
Thanks for reporting this @siebenmann. I'll need to think what is the minimum version of git I'm willing to support. So far I've been following suit with whatever the version of `git` that Apple ships with current Xcode (which is usually slightly old, updated mostly when there are critical security issues found).

Meanwhile, I'll see if I can find a workaround for this. I switched to the new command in order to be able to reliably tell when the origin remote doesn't exist. (Of course, that requires the command to be supported.)

**Comment by siebenmann** [comment]
Is there any good way to detect the git version (or that git-remote doesn't support the get-url command) and fall back to the old approach in that situation? git-remote exits with status 129 in this situation, but I don't know if it can exit with that status in other situations too.

(Most errors seem to cause it to exit with status 128, like 'no such remote' or 'not a git repo'.)

**Comment by dmitshur** [comment]
There is a way to check the available git version. I already [check the binary exists](https://github.com/shurcooL/vcsstate/blob/80ebbe9a32cc665d29da8acd66155331974fa7f8/git.go#L15) when library initializes; I could also check its version.

The biggest thing is that I don't want to significantly burden the maintenance cost of this library by having multiple code paths depending on the version of git. It'd be much harder to test, etc. It's better to just find something that works for older versions of git and use that.

Anyway, I've made a PR that fixes this issue, take a look.
